"""Alembic revision template for autogenerated database migrations."""

from alembic import op
import sqlalchemy as sa


revision = "5c1500f53f0e"
down_revision = "795d4070169d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "vehicles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("registration_number", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("manufacturer", sa.String(length=255), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "IN_USE",
                "MAINTENANCE",
                "OUT_OF_SERVICE",
                name="vehicle_status",
            ),
            server_default="AVAILABLE",
            nullable=False,
        ),
        sa.Column("current_latitude", sa.Float(), nullable=True),
        sa.Column("current_longitude", sa.Float(), nullable=True),
        sa.Column("fuel_level", sa.Float(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_vehicles_created_at",
        "vehicles",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_vehicles_is_active",
        "vehicles",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vehicles_registration_number"),
        "vehicles",
        ["registration_number"],
        unique=True,
    )
    op.create_index(
        "ix_vehicles_status",
        "vehicles",
        ["status"],
        unique=False,
    )

    op.create_table(
        "drivers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("license_number", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "BUSY",
                "OFFLINE",
                name="driver_status",
            ),
            server_default="AVAILABLE",
            nullable=False,
        ),
        sa.Column("current_latitude", sa.Float(), nullable=True),
        sa.Column("current_longitude", sa.Float(), nullable=True),
        sa.Column("max_capacity", sa.Integer(), nullable=False),
        sa.Column(
            "is_available",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )

    op.create_index(
        "ix_drivers_created_at",
        "drivers",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_drivers_is_available",
        "drivers",
        ["is_available"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drivers_license_number"),
        "drivers",
        ["license_number"],
        unique=True,
    )
    op.create_index(
        "ix_drivers_status",
        "drivers",
        ["status"],
        unique=False,
    )

    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("customer_phone", sa.String(length=32), nullable=False),
        sa.Column("pickup_address", sa.Text(), nullable=False),
        sa.Column("delivery_address", sa.Text(), nullable=False),
        sa.Column("pickup_latitude", sa.Float(), nullable=False),
        sa.Column("pickup_longitude", sa.Float(), nullable=False),
        sa.Column("delivery_latitude", sa.Float(), nullable=False),
        sa.Column("delivery_longitude", sa.Float(), nullable=False),
        sa.Column("demand", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="1", nullable=False),
        sa.Column("time_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ASSIGNED",
                "IN_TRANSIT",
                "DELIVERED",
                "CANCELLED",
                name="order_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("assigned_driver_id", sa.UUID(), nullable=True),
        sa.Column("assigned_vehicle_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_latitude >= -90 AND delivery_latitude <= 90",
            name="ck_delivery_latitude",
        ),
        sa.CheckConstraint(
            "delivery_longitude >= -180 AND delivery_longitude <= 180",
            name="ck_delivery_longitude",
        ),
        sa.CheckConstraint(
            "demand > 0",
            name="ck_orders_demand_positive",
        ),
        sa.CheckConstraint(
            "pickup_latitude >= -90 AND pickup_latitude <= 90",
            name="ck_pickup_latitude",
        ),
        sa.CheckConstraint(
            "pickup_longitude >= -180 AND pickup_longitude <= 180",
            name="ck_pickup_longitude",
        ),
        sa.CheckConstraint(
            "priority >= 1",
            name="ck_orders_priority_minimum",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_driver_id"],
            ["drivers.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_vehicle_id"],
            ["vehicles.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_orders_created_at",
        "orders",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_orders_priority",
        "orders",
        ["priority"],
        unique=False,
    )
    op.create_index(
        "ix_orders_status",
        "orders",
        ["status"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index("ix_orders_priority", table_name="orders")
    op.drop_index("ix_orders_created_at", table_name="orders")
    op.drop_table("orders")

    op.drop_index("ix_drivers_status", table_name="drivers")
    op.drop_index(op.f("ix_drivers_license_number"), table_name="drivers")
    op.drop_index("ix_drivers_is_available", table_name="drivers")
    op.drop_index("ix_drivers_created_at", table_name="drivers")
    op.drop_table("drivers")

    op.drop_index("ix_vehicles_status", table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_registration_number"), table_name="vehicles")
    op.drop_index("ix_vehicles_is_active", table_name="vehicles")
    op.drop_index("ix_vehicles_created_at", table_name="vehicles")
    op.drop_table("vehicles")