"""Alembic revision template for autogenerated database migrations."""

from alembic import op
import sqlalchemy as sa


revision = '795d4070169d'
down_revision = 'b96b0e9da45c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
